server:
  port: ${BOOT_PORT:${PICKUP_BOT_SERVICE_PORT:777}}

spring:
  application:
    name: bot
  profiles:
    active: default

bot:
  telegramTokenName: IMRemindBot
  telegramTokenValue: 1058251631:AAEk-5t2lUb3yujZIgHJCwQG50LeNVlwjHg
